# Identidade Visual Institucional - PharmaStation (Teal Moderno #0B949E)
@accentColor=#0B949E
@defaultAccentColor=#0B949E
@focusColor=#0B949E
@selectionBackground=fade(@accentColor,25%)

Component.focusWidth=1
Component.arc=10
Component.focusColor=#0B949E
Component.focusedBorderColor=#0B949E

Button.arc=10
Button.margin=5,12,5,12
Button.default.background=#0B949E
Button.default.hoverBackground=#0DA5B0
Button.default.focusedBackground=#08838C
Button.default.foreground=#FFFFFF

TextComponent.arc=10
TextField.margin=5,8,5,8
FormattedTextField.margin=5,8,5,8
ComboBox.padding=5,8,5,8

Table.selectionBackground=fade(@accentColor,25%)
Table.selectionInactiveBackground=fade(@accentColor,15%)
Table.rowHeight=32

CheckBox.icon.selectedBackground=#0B949E
CheckBox.icon.selectedBorderColor=#0B949E
RadioButton.icon.selectedBackground=#0B949E
RadioButton.icon.selectedBorderColor=#0B949E

ScrollBar.thumb=fade(@accentColor,40%)
ScrollBar.thumbHover=fade(@accentColor,60%)

ScrollPane.TextComponent.arc=10
TextArea.margin=3,1,3,1
TextArea.arc=20
Toast.background=lighten(@background,5%)
